[package]
edition = "2021"
name = "chat"
version = "0.1.0"

[features]
fake = []
tauri = []
web = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bounce = "0.9.0"
chrono = "0.4.33"
fake = {version = "2.9.2", features = ["derive", "uuid", "chrono"]}
getrandom = {version = "0.2.12", features = ["js"]}
gloo-console = "0.3.0"
gloo-events = "0.2.0"
gloo-net = "0.5.0"
gloo-render = "0.2.0"
gloo-timers = "0.3.0"
gloo-utils = "0.2.0"
indexmap = "2.2.1"
js-sys = "0.3.67"
nanoid = "0.4.0"
rand = "0.8.5"
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.115"
stylist = {version = "0.13.0", features = ["yew_integration"]}
tauri-sys = {git = "https://github.com/JonasKruckenberg/tauri-sys", features = ["all"]}
wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.40"
web-sys = {version = "0.3.67", features = [
  "Document",
  "Element",
  "HtmlElement",
  "HtmlLiElement",
  "HtmlImageElement",
  "HtmlCanvasElement",
  "CanvasRenderingContext2d",
  "Window",
  "Url",
  "Navigator",
  "EventListener",
  "EventTarget",
  "DomStringMap",
  "CssStyleDeclaration",
]}
yew = {version = "0.21.0", features = ["csr"]}
yew-hooks = "0.3.0"
yew-scroll-area = "0.4.0"
yew_icons = {version = "0.8.0", features = [
  "BootstrapSunFill",
  "BootstrapMoonStarsFill",
  "FontAwesomeSolidDownload"
]}
